name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Generate Docs
        run: go run pkg/docgen/main.go

      - name: Commit Docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Update docs
          push_options: '--force'
