name: Tests

on:
  push:
    branches:
      - main
      - 'dev-*'
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Go Tests
        run: go test ./... -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: kubectl-rancherx-tests-coverage
          path: coverage.out

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Rancher
        run: .github/scripts/install-rancher.sh "v2.9-head"
