name: Tests

on:
  push:
    branches:
      - main
      - 'dev-*'
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Go Tests
        run: go test ./pkg/... -coverprofile=coverage.out # excludes ./e2e tests directory

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: kubectl-rancherx-tests-coverage
          path: coverage.out

  e2e-tests:
    runs-on: ubuntu-latest
    env:
      RANCHER_VERSION: v2.9-head
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      GOCOVERDIR: cover
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install Rancher
        run: .github/scripts/install-rancher.sh ${{ env.RANCHER_VERSION }}

      - name: Build rancherx
        run: sh scripts/build-cover.sh

      - name: Run tests suite
        run: go run github.com/onsi/ginkgo/v2/ginkgo -v e2e/rancher
